[package]
name = "jsar_jsbundle"
version = "1.0.0"
authors = ["The JSAR Project Developers"]
license = "Apache-2.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
name = "jsar_jsbundle"
crate-type = ["staticlib"]
path = "lib.rs"

[build-dependencies]
cbindgen = "^0.19.0"
