#pragma once

#define TR_COMMAND_BUFFER_REQUESTS_MAP(XX)                                                 \
  XX(WEBGL_CONTEXT_INIT, WebGL1ContextInitCommandBufferRequest)                            \
  XX(WEBGL2_CONTEXT_INIT, WebGL2ContextInitCommandBufferRequest)                           \
  XX(CREATE_PROGRAM, CreateProgramCommandBufferRequest)                                    \
  XX(DELETE_PROGRAM, DeleteProgramCommandBufferRequest)                                    \
  XX(LINK_PROGRAM, LinkProgramCommandBufferRequest)                                        \
  XX(USE_PROGRAM, UseProgramCommandBufferRequest)                                          \
  XX(GET_PROGRAM_PARAM, GetProgramParamCommandBufferRequest)                               \
  XX(GET_PROGRAM_INFO_LOG, GetProgramInfoLogCommandBufferRequest)                          \
  XX(ATTACH_SHADER, AttachShaderCommandBufferRequest)                                      \
  XX(DETACH_SHADER, DetachShaderCommandBufferRequest)                                      \
  XX(CREATE_SHADER, CreateShaderCommandBufferRequest)                                      \
  XX(DELETE_SHADER, DeleteShaderCommandBufferRequest)                                      \
  XX(SHADER_SOURCE, ShaderSourceCommandBufferRequest)                                      \
  XX(COMPILE_SHADER, CompileShaderCommandBufferRequest)                                    \
  XX(GET_SHADER_SOURCE, GetShaderSourceCommandBufferRequest)                               \
  XX(GET_SHADER_PARAM, GetShaderParamCommandBufferRequest)                                 \
  XX(GET_SHADER_INFO_LOG, GetShaderInfoLogCommandBufferRequest)                            \
  XX(CREATE_BUFFER, CreateBufferCommandBufferRequest)                                      \
  XX(DELETE_BUFFER, DeleteBufferCommandBufferRequest)                                      \
  XX(BIND_BUFFER, BindBufferCommandBufferRequest)                                          \
  XX(BUFFER_DATA, BufferDataCommandBufferRequest)                                          \
  XX(BUFFER_SUB_DATA, BufferSubDataCommandBufferRequest)                                   \
  XX(CREATE_FRAMEBUFFER, CreateFramebufferCommandBufferRequest)                            \
  XX(DELETE_FRAMEBUFFER, DeleteFramebufferCommandBufferRequest)                            \
  XX(BIND_FRAMEBUFFER, BindFramebufferCommandBufferRequest)                                \
  XX(FRAMEBUFFER_RENDERBUFFER, FramebufferRenderbufferCommandBufferRequest)                \
  XX(FRAMEBUFFER_TEXTURE2D, FramebufferTexture2DCommandBufferRequest)                      \
  XX(CHECK_FRAMEBUFFER_STATUS, CheckFramebufferStatusCommandBufferRequest)                 \
  XX(CREATE_RENDERBUFFER, CreateRenderbufferCommandBufferRequest)                          \
  XX(DELETE_RENDERBUFFER, DeleteRenderbufferCommandBufferRequest)                          \
  XX(BIND_RENDERBUFFER, BindRenderbufferCommandBufferRequest)                              \
  XX(RENDERBUFFER_STORAGE, RenderbufferStorageCommandBufferRequest)                        \
  XX(READ_BUFFER, ReadBufferCommandBufferRequest)                                          \
  XX(BIND_BUFFER_BASE, BindBufferBaseCommandBufferRequest)                                 \
  XX(BIND_BUFFER_RANGE, BindBufferRangeCommandBufferRequest)                               \
  XX(BLIT_FRAMEBUFFER, BlitFramebufferCommandBufferRequest)                                \
  XX(RENDERBUFFER_STORAGE_MULTISAMPLE, RenderbufferStorageMultisampleCommandBufferRequest) \
  XX(CREATE_VERTEX_ARRAY, CreateVertexArrayCommandBufferRequest)                           \
  XX(DELETE_VERTEX_ARRAY, DeleteVertexArrayCommandBufferRequest)                           \
  XX(BIND_VERTEX_ARRAY, BindVertexArrayCommandBufferRequest)                               \
  XX(CREATE_TEXTURE, CreateTextureCommandBufferRequest)                                    \
  XX(DELETE_TEXTURE, DeleteTextureCommandBufferRequest)                                    \
  XX(BIND_TEXTURE, BindTextureCommandBufferRequest)                                        \
  XX(TEXTURE_IMAGE_2D, TextureImage2DCommandBufferRequest)                                 \
  XX(TEXTURE_SUB_IMAGE_2D, TextureSubImage2DCommandBufferRequest)                          \
  XX(COPY_TEXTURE_IMAGE_2D, CopyTextureImage2DCommandBufferRequest)                        \
  XX(COPY_TEXTURE_SUB_IMAGE_2D, CopyTextureSubImage2DCommandBufferRequest)                 \
  XX(TEXTURE_PARAMETERI, TextureParameteriCommandBufferRequest)                            \
  XX(ACTIVE_TEXTURE, ActiveTextureCommandBufferRequest)                                    \
  XX(GENERATE_MIPMAP, GenerateMipmapCommandBufferRequest)                                  \
  XX(TEXTURE_IMAGE_3D, TextureImage3DCommandBufferRequest)                                 \
  XX(TEXTURE_SUB_IMAGE_3D, TextureSubImage3DCommandBufferRequest)                          \
  XX(ENABLE_VERTEX_ATTRIB_ARRAY, EnableVertexAttribArrayCommandBufferRequest)              \
  XX(DISABLE_VERTEX_ATTRIB_ARRAY, DisableVertexAttribArrayCommandBufferRequest)            \
  XX(VERTEX_ATTRIB_POINTER, VertexAttribPointerCommandBufferRequest)                       \
  XX(VERTEX_ATTRIB_IPOINTER, VertexAttribIPointerCommandBufferRequest)                     \
  XX(VERTEX_ATTRIB_DIVISOR, VertexAttribDivisorCommandBufferRequest)                       \
  XX(UNIFORM_BLOCK_BINDING, UniformBlockBindingCommandBufferRequest)                       \
  XX(UNIFORM1F, Uniform1fCommandBufferRequest)                                             \
  XX(UNIFORM1FV, Uniform1fvCommandBufferRequest)                                           \
  XX(UNIFORM1I, Uniform1iCommandBufferRequest)                                             \
  XX(UNIFORM1IV, Uniform1ivCommandBufferRequest)                                           \
  XX(UNIFORM2F, Uniform2fCommandBufferRequest)                                             \
  XX(UNIFORM2FV, Uniform2fvCommandBufferRequest)                                           \
  XX(UNIFORM2I, Uniform2iCommandBufferRequest)                                             \
  XX(UNIFORM2IV, Uniform2ivCommandBufferRequest)                                           \
  XX(UNIFORM3F, Uniform3fCommandBufferRequest)                                             \
  XX(UNIFORM3FV, Uniform3fvCommandBufferRequest)                                           \
  XX(UNIFORM3I, Uniform3iCommandBufferRequest)                                             \
  XX(UNIFORM3IV, Uniform3ivCommandBufferRequest)                                           \
  XX(UNIFORM4F, Uniform4fCommandBufferRequest)                                             \
  XX(UNIFORM4FV, Uniform4fvCommandBufferRequest)                                           \
  XX(UNIFORM4I, Uniform4iCommandBufferRequest)                                             \
  XX(UNIFORM4IV, Uniform4ivCommandBufferRequest)                                           \
  XX(UNIFORM_MATRIX2FV, UniformMatrix2fvCommandBufferRequest)                              \
  XX(UNIFORM_MATRIX3FV, UniformMatrix3fvCommandBufferRequest)                              \
  XX(UNIFORM_MATRIX4FV, UniformMatrix4fvCommandBufferRequest)                              \
  XX(DRAW_ARRAYS, DrawArraysCommandBufferRequest)                                          \
  XX(DRAW_ELEMENTS, DrawElementsCommandBufferRequest)                                      \
  XX(DRAW_ARRAYS_INSTANCED, DrawArraysInstancedCommandBufferRequest)                       \
  XX(DRAW_ELEMENTS_INSTANCED, DrawElementsInstancedCommandBufferRequest)                   \
  XX(DRAW_RANGE_ELEMENTS, DrawRangeElementsCommandBufferRequest)                           \
  XX(DRAW_BUFFERS, DrawBuffersCommandBufferRequest)                                        \
  XX(PIXEL_STOREI, PixelStoreiCommandBufferRequest)                                        \
  XX(POLYGON_OFFSET, PolygonOffsetCommandBufferRequest)                                    \
  XX(SET_VIEWPORT, SetViewportCommandBufferRequest)                                        \
  XX(SET_SCISSOR, SetScissorCommandBufferRequest)                                          \
  XX(GET_EXTENSIONS, GetExtensionsCommandBufferRequest)                                    \
  XX(DEPTH_MASK, DepthMaskCommandBufferRequest)                                            \
  XX(DEPTH_FUNC, DepthFuncCommandBufferRequest)                                            \
  XX(DEPTH_RANGE, DepthRangeCommandBufferRequest)                                          \
  XX(STENCIL_FUNC, StencilFuncCommandBufferRequest)                                        \
  XX(STENCIL_FUNC_SEPARATE, StencilFuncSeparateCommandBufferRequest)                       \
  XX(STENCIL_MASK, StencilMaskCommandBufferRequest)                                        \
  XX(STENCIL_MASK_SEPARATE, StencilMaskSeparateCommandBufferRequest)                       \
  XX(STENCIL_OP, StencilOpCommandBufferRequest)                                            \
  XX(STENCIL_OP_SEPARATE, StencilOpSeparateCommandBufferRequest)                           \
  XX(BLEND_COLOR, BlendColorCommandBufferRequest)                                          \
  XX(BLEND_EQUATION, BlendEquationCommandBufferRequest)                                    \
  XX(BLEND_EQUATION_SEPARATE, BlendEquationSeparateCommandBufferRequest)                   \
  XX(BLEND_FUNC, BlendFuncCommandBufferRequest)                                            \
  XX(BLEND_FUNC_SEPARATE, BlendFuncSeparateCommandBufferRequest)                           \
  XX(COLOR_MASK, ColorMaskCommandBufferRequest)                                            \
  XX(CULL_FACE, CullFaceCommandBufferRequest)                                              \
  XX(FRONT_FACE, FrontFaceCommandBufferRequest)                                            \
  XX(ENABLE, EnableCommandBufferRequest)                                                   \
  XX(DISABLE, DisableCommandBufferRequest)                                                 \
  XX(GET_BOOLEANV, GetBooleanvCommandBufferRequest)                                        \
  XX(GET_INTEGERV, GetIntegervCommandBufferRequest)                                        \
  XX(GET_FLOATV, GetFloatvCommandBufferRequest)                                            \
  XX(GET_STRING, GetStringCommandBufferRequest)                                            \
  XX(GET_SHADER_PRECISION_FORMAT, GetShaderPrecisionFormatCommandBufferRequest)            \
  XX(GET_ERROR, GetErrorCommandBufferRequest)                                              \
  XX(XRFRAME_START, XRFrameStartCommandBufferRequest)                                      \
  XX(XRFRAME_FLUSH, XRFrameFlushCommandBufferRequest)                                      \
  XX(XRFRAME_END, XRFrameEndCommandBufferRequest)
