#pragma once

#include <vector>

#include "idgen.hpp"
#include "common/ipc.hpp"

namespace commandbuffers
{
  class TrCommandBufferSender;
  class TrCommandBufferReceiver;
  class TrCommandBufferMessage;
  class TrCommandBufferSegment;
  class TrCommandBufferBase;
  class TrCommandBufferResponse;

  static TrIdGenerator commandBufferIdGen(1);

  enum CommandBufferType
  {
    /** Default */
    COMMAND_BUFFER_UNKNOWN = 0,

    /** Context */
    COMMAND_BUFFER_WEBGL_CONTEXT_INIT_REQ,
    COMMAND_BUFFER_WEBGL_CONTEXT_INIT_RES,
    COMMAND_BUFFER_WEBGL2_CONTEXT_INIT_REQ,
    COMMAND_BUFFER_WEBGL2_CONTEXT_INIT_RES,

    /** Extensions */
    COMMAND_BUFFER_GET_EXTENSIONS_REQ,
    COMMAND_BUFFER_GET_EXTENSIONS_RES,

    /** Program */
    COMMAND_BUFFER_CREATE_PROGRAM_REQ,
    COMMAND_BUFFER_DELETE_PROGRAM_REQ,
    COMMAND_BUFFER_LINK_PROGRAM_REQ,
    COMMAND_BUFFER_USE_PROGRAM_REQ,
    COMMAND_BUFFER_GET_PROGRAM_PARAM_REQ,
    COMMAND_BUFFER_GET_PROGRAM_PARAM_RES,
    COMMAND_BUFFER_GET_PROGRAM_INFO_LOG_REQ,
    COMMAND_BUFFER_GET_PROGRAM_INFO_LOG_RES,

    /** Shader */
    COMMAND_BUFFER_ATTACH_SHADER_REQ,
    COMMAND_BUFFER_DETACH_SHADER_REQ,
    COMMAND_BUFFER_CREATE_SHADER_REQ,
    COMMAND_BUFFER_DELETE_SHADER_REQ,
    COMMAND_BUFFER_SHADER_SOURCE_REQ,
    COMMAND_BUFFER_COMPILE_SHADER_REQ,
    COMMAND_BUFFER_GET_SHADER_SOURCE_REQ,
    COMMAND_BUFFER_GET_SHADER_SOURCE_RES,
    COMMAND_BUFFER_GET_SHADER_PARAM_REQ,
    COMMAND_BUFFER_GET_SHADER_PARAM_RES,
    COMMAND_BUFFER_GET_SHADER_INFO_LOG_REQ,
    COMMAND_BUFFER_GET_SHADER_INFO_LOG_RES,

    /** Buffer */
    COMMAND_BUFFER_CREATE_BUFFER_REQ,
    COMMAND_BUFFER_DELETE_BUFFER_REQ,
    COMMAND_BUFFER_BIND_BUFFER_REQ,
    COMMAND_BUFFER_BUFFER_DATA_REQ,
    COMMAND_BUFFER_BUFFER_SUB_DATA_REQ,
    COMMAND_BUFFER_CREATE_FRAMEBUFFER_REQ,
    COMMAND_BUFFER_DELETE_FRAMEBUFFER_REQ,
    COMMAND_BUFFER_BIND_FRAMEBUFFER_REQ,

    /** Vertex Array */
    COMMAND_BUFFER_CREATE_VERTEX_ARRAY_REQ,
    COMMAND_BUFFER_DELETE_VERTEX_ARRAY_REQ,
    COMMAND_BUFFER_BIND_VERTEX_ARRAY_REQ,
  };
}
