export type ApiStream = AsyncGenerator<ApiStreamChunk>;
export type ApiStreamChunk = ApiStreamTextChunk | ApiStreamReasoningChunk | ApiStreamUsageChunk;

/**
 * The text chunk is the main chunk in the stream and contains the text generated by the model.
 */
export interface ApiStreamTextChunk {
  type: 'text'
  text: string
}

/**
 * The reasoning chunk is used to provide reasoning information during the stream.
 */
export interface ApiStreamReasoningChunk {
  type: 'reasoning'
  reasoning: string
}

/**
 * The usage chunk is the last chunk in the stream and contains the total number of tokens used by the request.
 * It is only included if the `stream` option is set to `true`.
 * @see URL_ADDRESS * @see https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream
 */
export interface ApiStreamUsageChunk {
  type: 'usage'
  inputTokens: number
  outputTokens: number
  cacheWriteTokens?: number
  cacheReadTokens?: number
  totalCost?: number // openrouter
}
