export type ApiProvider =
  | 'qwen'
  | 'doubao';
export interface ApiHandlerOptions {
  apiModelId?: string;
  qwenApiKey?: string;
  doubaoApiKey?: string;
  qwenApiLine?: string;
}

export type ApiConfiguration = ApiHandlerOptions & {
  apiProvider?: ApiProvider;
};
export interface ModelInfo {
  maxTokens?: number;
  contextWindow?: number;
  supportsImages?: boolean;
  supportsPromptCache: boolean; // this value is hardcoded for now
  inputPrice?: number; // Keep for non-tiered input models
  outputPrice?: number; // Keep for non-tiered output models
  cacheWritesPrice?: number;
  cacheReadsPrice?: number;
}

// Qwen
// https://bailian.console.aliyun.com/
export type MainlandQwenModelId = keyof typeof mainlandQwenModels;
export type InternationalQwenModelId = keyof typeof internationalQwenModels;
export const internationalQwenDefaultModelId: InternationalQwenModelId = 'qwen-coder-plus-latest';
export const mainlandQwenDefaultModelId: MainlandQwenModelId = 'qwen-coder-plus-latest';
export const internationalQwenModels = {
  'qwen3-235b-a22b': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.002,
    outputPrice: 0.006,
    cacheWritesPrice: 0.002,
    cacheReadsPrice: 0.006,
  },
  'qwen2.5-coder-32b-instruct': {
    maxTokens: 8_192,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.002,
    outputPrice: 0.006,
    cacheWritesPrice: 0.002,
    cacheReadsPrice: 0.006,
  },
  'qwen2.5-coder-14b-instruct': {
    maxTokens: 8_192,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.002,
    outputPrice: 0.006,
    cacheWritesPrice: 0.002,
    cacheReadsPrice: 0.006,
  },
  'qwen2.5-coder-7b-instruct': {
    maxTokens: 8_192,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.001,
    outputPrice: 0.002,
    cacheWritesPrice: 0.001,
    cacheReadsPrice: 0.002,
  },
  'qwen2.5-coder-3b-instruct': {
    maxTokens: 8_192,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwen2.5-coder-1.5b-instruct': {
    maxTokens: 8_192,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwen2.5-coder-0.5b-instruct': {
    maxTokens: 8_192,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwen-coder-plus-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 3.5,
    outputPrice: 7,
    cacheWritesPrice: 3.5,
    cacheReadsPrice: 7,
  },
  'qwen-plus-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.8,
    outputPrice: 2,
    cacheWritesPrice: 0.8,
    cacheReadsPrice: 0.2,
  },
  'qwen-turbo-latest': {
    maxTokens: 1_000_000,
    contextWindow: 1_000_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.8,
    outputPrice: 2,
    cacheWritesPrice: 0.8,
    cacheReadsPrice: 2,
  },
  'qwen-max-latest': {
    maxTokens: 30_720,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 2.4,
    outputPrice: 9.6,
    cacheWritesPrice: 2.4,
    cacheReadsPrice: 9.6,
  },
  'qwen-coder-plus': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 3.5,
    outputPrice: 7,
    cacheWritesPrice: 3.5,
    cacheReadsPrice: 7,
  },
  'qwen-plus': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.8,
    outputPrice: 2,
    cacheWritesPrice: 0.8,
    cacheReadsPrice: 0.2,
  },
  'qwen-turbo': {
    maxTokens: 1_000_000,
    contextWindow: 1_000_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.3,
    outputPrice: 0.6,
    cacheWritesPrice: 0.3,
    cacheReadsPrice: 0.6,
  },
  'qwen-max': {
    maxTokens: 30_720,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 2.4,
    outputPrice: 9.6,
    cacheWritesPrice: 2.4,
    cacheReadsPrice: 9.6,
  },
  'deepseek-v3': {
    maxTokens: 8_000,
    contextWindow: 64_000,
    supportsImages: false,
    supportsPromptCache: true,
    inputPrice: 0,
    outputPrice: 0.28,
    cacheWritesPrice: 0.14,
    cacheReadsPrice: 0.014,
  },
  'deepseek-r1': {
    maxTokens: 8_000,
    contextWindow: 64_000,
    supportsImages: false,
    supportsPromptCache: true,
    inputPrice: 0,
    outputPrice: 2.19,
    cacheWritesPrice: 0.55,
    cacheReadsPrice: 0.14,
  },
  'qwen-vl-max': {
    maxTokens: 30_720,
    contextWindow: 32_768,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 3,
    outputPrice: 9,
    cacheWritesPrice: 3,
    cacheReadsPrice: 9,
  },
  'qwen-vl-max-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 3,
    outputPrice: 9,
    cacheWritesPrice: 3,
    cacheReadsPrice: 9,
  },
  'qwen-vl-plus': {
    maxTokens: 6_000,
    contextWindow: 8_000,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 1.5,
    outputPrice: 4.5,
    cacheWritesPrice: 1.5,
    cacheReadsPrice: 4.5,
  },
  'qwen-vl-plus-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 1.5,
    outputPrice: 4.5,
    cacheWritesPrice: 1.5,
    cacheReadsPrice: 4.5,
  },
} as const satisfies Record<string, ModelInfo>;

export const mainlandQwenModels = {
  'qwen2.5-coder-32b-instruct': {
    maxTokens: 8_192,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.002,
    outputPrice: 0.006,
    cacheWritesPrice: 0.002,
    cacheReadsPrice: 0.006,
  },
  'qwen2.5-coder-14b-instruct': {
    maxTokens: 8_192,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.002,
    outputPrice: 0.006,
    cacheWritesPrice: 0.002,
    cacheReadsPrice: 0.006,
  },
  'qwen2.5-coder-7b-instruct': {
    maxTokens: 8_192,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.001,
    outputPrice: 0.002,
    cacheWritesPrice: 0.001,
    cacheReadsPrice: 0.002,
  },
  'qwen2.5-coder-3b-instruct': {
    maxTokens: 8_192,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwen2.5-coder-1.5b-instruct': {
    maxTokens: 8_192,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwen2.5-coder-0.5b-instruct': {
    maxTokens: 8_192,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwen-coder-plus-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 3.5,
    outputPrice: 7,
    cacheWritesPrice: 3.5,
    cacheReadsPrice: 7,
  },
  'qwen-plus-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.8,
    outputPrice: 2,
    cacheWritesPrice: 0.8,
    cacheReadsPrice: 0.2,
  },
  'qwen-turbo-latest': {
    maxTokens: 1_000_000,
    contextWindow: 1_000_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.8,
    outputPrice: 2,
    cacheWritesPrice: 0.8,
    cacheReadsPrice: 2,
  },
  'qwen-max-latest': {
    maxTokens: 30_720,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 2.4,
    outputPrice: 9.6,
    cacheWritesPrice: 2.4,
    cacheReadsPrice: 9.6,
  },
  'qwq-plus-latest': {
    maxTokens: 8_192,
    contextWindow: 131_071,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwq-plus': {
    maxTokens: 8_192,
    contextWindow: 131_071,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    cacheWritesPrice: 0.0,
    cacheReadsPrice: 0.0,
  },
  'qwen-coder-plus': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 3.5,
    outputPrice: 7,
    cacheWritesPrice: 3.5,
    cacheReadsPrice: 7,
  },
  'qwen-plus': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.8,
    outputPrice: 2,
    cacheWritesPrice: 0.8,
    cacheReadsPrice: 0.2,
  },
  'qwen-turbo': {
    maxTokens: 1_000_000,
    contextWindow: 1_000_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.3,
    outputPrice: 0.6,
    cacheWritesPrice: 0.3,
    cacheReadsPrice: 0.6,
  },
  'qwen-max': {
    maxTokens: 30_720,
    contextWindow: 32_768,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 2.4,
    outputPrice: 9.6,
    cacheWritesPrice: 2.4,
    cacheReadsPrice: 9.6,
  },
  'deepseek-v3': {
    maxTokens: 8_000,
    contextWindow: 64_000,
    supportsImages: false,
    supportsPromptCache: true,
    inputPrice: 0,
    outputPrice: 0.28,
    cacheWritesPrice: 0.14,
    cacheReadsPrice: 0.014,
  },
  'deepseek-r1': {
    maxTokens: 8_000,
    contextWindow: 64_000,
    supportsImages: false,
    supportsPromptCache: true,
    inputPrice: 0,
    outputPrice: 2.19,
    cacheWritesPrice: 0.55,
    cacheReadsPrice: 0.14,
  },
  'qwen-vl-max': {
    maxTokens: 30_720,
    contextWindow: 32_768,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 3,
    outputPrice: 9,
    cacheWritesPrice: 3,
    cacheReadsPrice: 9,
  },
  'qwen-vl-max-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 3,
    outputPrice: 9,
    cacheWritesPrice: 3,
    cacheReadsPrice: 9,
  },
  'qwen-vl-plus': {
    maxTokens: 6_000,
    contextWindow: 8_000,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 1.5,
    outputPrice: 4.5,
    cacheWritesPrice: 1.5,
    cacheReadsPrice: 4.5,
  },
  'qwen-vl-plus-latest': {
    maxTokens: 129_024,
    contextWindow: 131_072,
    supportsImages: true,
    supportsPromptCache: false,
    inputPrice: 1.5,
    outputPrice: 4.5,
    cacheWritesPrice: 1.5,
    cacheReadsPrice: 4.5,
  },
} as const satisfies Record<string, ModelInfo>;

// Doubao
// https://www.volcengine.com/docs/82379/1298459
// https://console.volcengine.com/ark/region:ark+cn-beijing/openManagement
export type DoubaoModelId = keyof typeof doubaoModels;
export const doubaoDefaultModelId: DoubaoModelId = 'doubao-1-5-pro-256k-250115';
export const doubaoModels = {
  'doubao-1-5-pro-256k-250115': {
    maxTokens: 12_288,
    contextWindow: 256_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.7,
    outputPrice: 1.3,
    cacheWritesPrice: 0,
    cacheReadsPrice: 0,
  },
  'doubao-1-5-pro-32k-250115': {
    maxTokens: 12_288,
    contextWindow: 32_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.11,
    outputPrice: 0.3,
    cacheWritesPrice: 0,
    cacheReadsPrice: 0,
  },
  'deepseek-v3-250324': {
    maxTokens: 12_288,
    contextWindow: 128_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.55,
    outputPrice: 2.19,
    cacheWritesPrice: 0,
    cacheReadsPrice: 0,
  },
  'deepseek-r1-250120': {
    maxTokens: 32_768,
    contextWindow: 64_000,
    supportsImages: false,
    supportsPromptCache: false,
    inputPrice: 0.27,
    outputPrice: 1.09,
    cacheWritesPrice: 0,
    cacheReadsPrice: 0,
  },
} as const satisfies Record<string, ModelInfo>;
