#pragma once

#include <memory>
#include <vector>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/geometric.hpp>

#include <OpenGL/gl3.h>
#include <GLFW/glfw3.h>

#include "./content_bar_canvas.hpp"

namespace jsar::example
{
  class Content;
  class ContentBarCanvas;

  /**
   * ContentBar3d handles the 3D scene integration aspect of content bars.
   * Responsible for OpenGL rendering, 3D positioning, instanced rendering, and ray intersection.
   * Uses textures generated by ContentBarCanvas for visual representation.
   * All 3D scene logic is implemented here, decoupled from UI rendering.
   */
  class ContentBar3d
  {
  public:
    ContentBar3d(std::shared_ptr<ContentBarCanvas> canvas);
    ~ContentBar3d();

    /**
     * Add a content instance to be rendered with a bar in 3D space.
     */
    void addContent(Content *content);

    /**
     * Remove a content instance from 3D rendering.
     */
    void removeContent(Content *content);

    /**
     * Update the 3D transformation matrix for a specific content's bar.
     */
    void updateContentTransform(Content *content, const glm::mat4 &transform);

    /**
     * Render all bars using instanced rendering in 3D space.
     */
    void renderInstanced(const glm::mat4 &viewMatrix, const glm::mat4 &projectionMatrix);

    /**
     * Check if a 3D ray intersects with any bar and return the content.
     * This is the 3D interaction entry point for the event proxy.
     */
    Content *checkRayIntersection(const glm::vec3 &rayOrigin, const glm::vec3 &rayDirection) const;

    /**
     * Set the visual state for a specific content's bar.
     * This forwards the state to the canvas component via event proxy.
     */
    void setContentHovered(Content *content, bool hovered);
    void setContentDragging(Content *content, bool dragging);

  private:
    struct BarInstance
    {
      Content *content;
      glm::mat4 transform;
      bool isHovered;
      bool isDragging;

      BarInstance(Content *c)
          : content(c)
          , transform(1.0f)
          , isHovered(false)
          , isDragging(false)
      {
      }
    };

    void initGLProgram();
    void createGeometry();
    void updateInstanceBuffer();
    void updateTextureFromCanvas();
    glm::mat4 calculateBarTransform(const glm::vec3 &contentPosition) const;

  private:
    std::shared_ptr<ContentBarCanvas> canvas_;
    std::vector<BarInstance> instances_;

    // OpenGL resources for instanced rendering
    GLuint vao_;
    GLuint vertexVBO_;   // Vertex data for the bar quad
    GLuint instanceVBO_; // Instance transformation matrices and states
    GLuint program_;
    GLuint barTexture_; // Texture from ContentBarCanvas

    // Shader uniforms
    GLint viewMatrixLoc_;
    GLint projectionMatrixLoc_;
    GLint textureLoc_;

    // 3D bar properties
    static constexpr float BAR_WIDTH = 0.20f;     // World space width
    static constexpr float BAR_HEIGHT = 0.005f;   // World space height
    static constexpr float BAR_OFFSET_Y = -0.16f; // Offset below content in world space

    // Vertex data for a quad
    std::vector<float> vertices_;

    // Shaders for 3D rendering
    const char *barVertSource_;
    const char *barFragSource_;
  };
}