name: Build library for Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.74.0
        target: aarch64-linux-android
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Set up Android NDK 17r
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: 'r17'
    - name: Set up Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: "21.x"
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
    - name: Install Node.js dependencies
      run: npm ci && npx tsc --version
    - name: Build JS Bundles
      run: |
        make jsbundle
    - name: Build library for Android
      run: |
        protoc --version
        make android
      env:
        USE_SYSTEM_PROTOC: "true"
