name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.74.0
        components: rustfmt
    - name: Install Rust targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
        rustup target add x86_64-pc-windows-msvc
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: 18.16.0
    - name: Install Node.js dependencies
      run: npm ci && npx tsc --version
    - name: Build JavaScript bundle
      run: |
        make jsbundle
    - name: Build Rust crates
      run: |
        make crates
        ls -lh ./build/output/crates
        ls -lh ./build/output/headers/crates
